identifier: k8u7w5o7371abbh4
allowErrorCollect: true
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: ang2-mohitkanwar
homeFolder: /Users/mohitk/projects/mohitkanwar-personal-webapp
distFolder: dist/public
outDir: /Users/mohitk/projects/mohitkanwar-personal-webapp/dist/static
handle404: ''
